version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.7.0
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: $DATABASE_URL
      PG_DATABASE_URL: $DATABASE_URL
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
