name: Heartbeat

on:
  schedule:
    - cron: '12 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: "curl -X GET -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scHB6Y2RldGJ2cm56bWR5YmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTgxMjc0NTgsImV4cCI6MTk3MzcwMzQ1OH0.gEglk_ua07blazFsZy5tAsr9VAX5VPQ3CRWR2yhcVes' https://peredoz.netlify.app/api/rest/v1/track?select=*"
